/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.EmpleadoDAO;

import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

import modelos.Empleado;




public class RegistroE extends javax.swing.JFrame {

    /**
     * Creates new form RegistroE
     */
    DefaultListModel modeloEmpleados = new DefaultListModel();
    ArrayList<Empleado> GuardarEmpleados = new ArrayList<>();
    
    
    public RegistroE() {
        initComponents();
        CrearModelo();
        setLocationRelativeTo(null);

    }
    
   private void CrearModelo(){
   
  
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEmpleados = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTRO DE EMPLEADOS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(140, 40, 203, 23);

        btnAgregar.setText("Agregar nuevo ");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(30, 80, 170, 23);

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(360, 80, 90, 23);

        lstEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lstEmpleados);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 113, 449, 206);

        setBounds(0, 0, 485, 369);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
     
    vAddEmpl NewEmpl= new vAddEmpl();
        NewEmpl.setVisible(true);
        
        
        
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
      
       EmpleadoDAO empl = new EmpleadoDAO();
      
        try {
            empl.listar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistroE.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            GuardarEmpleados=empl.listar();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(RegistroE.class.getName()).log(Level.SEVERE, null, ex);
        }
        modeloEmpleados.clear();
        
        for (Empleado emp : GuardarEmpleados) {
            modeloEmpleados.addElement(emp.getNombre() + "-id:" + emp.getId());}
            lstEmpleados.setModel(modeloEmpleados);

       
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void lstEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstEmpleadosMouseClicked
        Empleado empleado = new Empleado();
        String[] d = lstEmpleados.getSelectedValue().split("-");
        int id = Integer.parseInt(d[1].split(":")[1]);
        for (Empleado em : GuardarEmpleados) {
            if (em.getId()==id){
                empleado = em;
                break;
            }
        }
        new vManageEmpl(empleado).setVisible(true);             // TODO add your handling code here:
    }//GEN-LAST:event_lstEmpleadosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistroE.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistroE().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> lstEmpleados;
    // End of variables declaration//GEN-END:variables
}
