/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Conexion;
import controlador.EmpleadoDAO;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelos.Empleado;

/**
 *
 * @author Familia Pozuelo
 */
public class vManageEmpl extends javax.swing.JFrame {
     static Empleado empl;
  
    public vManageEmpl(Empleado empl) {
        
    
        this.empl = empl;
        initComponents();
        
        this.idEmpleado.setText(String.valueOf(empl.getId()));
        this.txtNombresC.setText(empl.getNombre());
        this.txtApellidosC.setText(empl.getApellido());
        this.txtCorreoC.setText(empl.getCorreo());
        this.txtCelularC.setText(empl.getCelular());
        this.chkProovedorC.setSelected(empl.getEsProveedor());
        this.txtSalarioC.setText(empl.getSalario());
        this.txtCargoC.setText(empl.getCargo());
        
       
    }
    /**
     * Creates new form vManageEmpl
     */
    public vManageEmpl() {
        initComponents();
        setLocationRelativeTo(null);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSalario = new javax.swing.JTextField();
        txtCargo = new javax.swing.JTextField();
        chkProovedor = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        chkProovedorC = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtNombresC = new javax.swing.JTextField();
        txtApellidosC = new javax.swing.JTextField();
        txtCorreoC = new javax.swing.JTextField();
        txtCelularC = new javax.swing.JTextField();
        txtCargoC = new javax.swing.JTextField();
        txtSalarioC = new javax.swing.JTextField();
        btnEditar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        idEmpleado = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        chkProovedor.setText("Proovedor");
        chkProovedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProovedorActionPerformed(evt);
            }
        });

        jLabel4.setText("Cargo:");

        jLabel5.setText("Salario*:");

        jLabel6.setText("Celular*:");

        jLabel2.setText("Apellidos:");

        jLabel1.setText("Nombres*:");

        jLabel3.setText("Correo*:");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        chkProovedorC.setText("Proovedor");
        chkProovedorC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkProovedorCActionPerformed(evt);
            }
        });
        getContentPane().add(chkProovedorC);
        chkProovedorC.setBounds(50, 170, 75, 23);

        jLabel7.setText("Cargo:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 200, 40, 14);

        jLabel8.setText("Salario*:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(230, 153, 60, 14);

        jLabel9.setText("Celular*:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(230, 93, 50, 14);

        jLabel10.setText("Apellidos:");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 33, 50, 14);

        jLabel11.setText("Nombres*:");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 33, 60, 14);

        jLabel12.setText("Correo*:");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 90, 50, 14);

        txtNombresC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombresCKeyTyped(evt);
            }
        });
        getContentPane().add(txtNombresC);
        txtNombresC.setBounds(10, 53, 165, 25);

        txtApellidosC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtApellidosCKeyTyped(evt);
            }
        });
        getContentPane().add(txtApellidosC);
        txtApellidosC.setBounds(230, 53, 165, 25);
        getContentPane().add(txtCorreoC);
        txtCorreoC.setBounds(10, 113, 165, 25);

        txtCelularC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCelularCActionPerformed(evt);
            }
        });
        txtCelularC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularCKeyTyped(evt);
            }
        });
        getContentPane().add(txtCelularC);
        txtCelularC.setBounds(230, 113, 165, 25);

        txtCargoC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCargoCActionPerformed(evt);
            }
        });
        txtCargoC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCargoCKeyTyped(evt);
            }
        });
        getContentPane().add(txtCargoC);
        txtCargoC.setBounds(10, 223, 165, 25);

        txtSalarioC.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSalarioCKeyTyped(evt);
            }
        });
        getContentPane().add(txtSalarioC);
        txtSalarioC.setBounds(230, 173, 165, 25);

        btnEditar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditar.setText("Actualizar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar);
        btnEditar.setBounds(60, 280, 116, 35);

        btnEliminar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEliminar.setText("Eliminar ");
        btnEliminar.setActionCommand("Eliminar ");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEliminar);
        btnEliminar.setBounds(230, 280, 81, 35);

        idEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idEmpleado.setText("Empleado ");
        getContentPane().add(idEmpleado);
        idEmpleado.setBounds(195, 13, 63, 15);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Empleado:");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(116, 11, 73, 17);

        setBounds(0, 0, 424, 381);
    }// </editor-fold>//GEN-END:initComponents

    private void chkProovedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProovedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProovedorActionPerformed

    private void chkProovedorCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkProovedorCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkProovedorCActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try { 
             Conexion con = new Conexion();
        
        con.conectar();
            
        //Conecto a BD
        try {
            PreparedStatement psm = con.getConexion().prepareStatement("DELETE FROM empleados WHERE celular=?");
            psm.setString(1,txtCelularC.getText());
            psm.executeUpdate();
            
        } catch (SQLException ex) {
            Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
        //Cerrar conexión
       con.cerrarConexion();
       } catch (ClassNotFoundException ex) {
         Logger.getLogger(Empleado.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        JOptionPane.showMessageDialog(this, "Empleado eliminado!");
       this.dispose();
        
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       
        
        Empleado empl = new Empleado();
        
        //Guardo los datos de la vista en el objeto Empleado
       
        empl.setId(Long.parseLong(idEmpleado.getText()));
        empl.setNombre(txtNombresC.getText());
        empl.setApellido(txtApellidosC.getText());
        empl.setCorreo(txtCorreoC.getText());
        empl.setCelular(txtCelularC.getText());
        empl.setCargo(txtCargoC.getText());
        empl.setSalario(txtSalarioC.getText());
        empl.setEsProveedor(chkProovedorC.isSelected());
        
        
       
        
        if(txtNombresC.getText().equals("") || txtCorreoC.getText().equals("")||txtCelularC.getText().equals("")||txtSalarioC.getText().equals("")) {

                     JOptionPane.showMessageDialog(this, "Por favor, dilegenciar correctamente el formulario");
                    }
        
        else{
        if (EmpleadoDAO.editar(empl)){
         JOptionPane.showMessageDialog(this, "Actualizado exitosamente");
         this.dispose();
            
        } 
        else{ JOptionPane.showMessageDialog(this, "*ERROR*"
                + "\nNo se pudo actualizar");}
        }
        
        
        
        
    }//GEN-LAST:event_btnEditarActionPerformed

    private void txtCelularCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCelularCActionPerformed

 

    }//GEN-LAST:event_txtCelularCActionPerformed

    private void txtCelularCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularCKeyTyped
   
        char n=evt.getKeyChar();
        if (!Character.isDigit(n)){ evt.consume();}        
    }//GEN-LAST:event_txtCelularCKeyTyped

    private void txtSalarioCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSalarioCKeyTyped
     
        
        char n=evt.getKeyChar();
        if (!Character.isDigit(n)){ evt.consume();}
    }//GEN-LAST:event_txtSalarioCKeyTyped

    private void txtApellidosCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtApellidosCKeyTyped
  char c = evt.getKeyChar();
if((c< 'a' || c>'z') && (c< 'A' || c>'Z')&& (c>' ')&&(c<'á'||c>'ú')&&(c<'Á'||c>'Ú')) evt.consume();       
    }//GEN-LAST:event_txtApellidosCKeyTyped

    private void txtNombresCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresCKeyTyped
  char c = evt.getKeyChar();
if((c< 'a' || c>'z') && (c< 'A' || c>'Z')&& (c>' ')&&(c<'á'||c>'ú')&&(c<'Á'||c>'Ú')) evt.consume();        
    }//GEN-LAST:event_txtNombresCKeyTyped

    private void txtCargoCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCargoCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCargoCActionPerformed

    private void txtCargoCKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCargoCKeyTyped
       char c = evt.getKeyChar();
if((c< 'a' || c>'z') && (c< 'A' || c>'Z')&& (c>' ')&&(c<'á'||c>'ú')&&(c<'Á'||c>'Ú')) evt.consume();  
    }//GEN-LAST:event_txtCargoCKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vManageEmpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vManageEmpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vManageEmpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vManageEmpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vManageEmpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JCheckBox chkProovedor;
    private javax.swing.JCheckBox chkProovedorC;
    private javax.swing.JLabel idEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtApellidosC;
    private javax.swing.JTextField txtCargo;
    private javax.swing.JTextField txtCargoC;
    private javax.swing.JTextField txtCelularC;
    private javax.swing.JTextField txtCorreoC;
    private javax.swing.JTextField txtNombresC;
    private javax.swing.JTextField txtSalario;
    private javax.swing.JTextField txtSalarioC;
    // End of variables declaration//GEN-END:variables
}
